name: stock
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib=3.0.0
  - pandas=0.23.4
  - python=3.5.5
  - requests=2.24.0
  - scikit-learn=0.20.0
  - pip:
      - requests-html
      - yahoo-fin==0.8.6

