name: stock
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib=1.5.3
  - pandas=0.23.4
  - python=3.5.5
  - requests
  - scikit-learn=0.20.0
  - pip:
      - requests-html
      - yahoo-fin

